name: run android tests in github runner

on: push

jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
            - run: |
                cwd=$(pwd)
                pushd "$cwd"
                cd ~
                appium driver install --source=local "$cwd"
                appium driver doctor uiautomator2
                nohup appium server \
                  --port=$APPIUM_TEST_SERVER_PORT \
                  --address=$APPIUM_TEST_SERVER_HOST \
                  --relaxed-security \
                  --log-no-colors \
                  --log-timestamp \
                  2>&1 > "$cwd/appium.log" &
                popd

      - name: pull the project into the runner
        uses: actions/checkout@v3
        
      - name: setup appium
        run: |
          npm install -g appium@2.0.0
          appium -v
          appium &>/dev/null &

      - name: run Appium tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn test -DxmlFilePath=TestNG
